config/routes.rb
Rails.application.routes.draw do
  
  root 'home#top'
  get 'home/about'
  devise_for :users
  resources :users
  get 'users/:id/follows'=> 'users#follows', as: 'follows'
  get 'users/:id/followers'=> 'users#followers', as: 'followers'
  
  resources :books do
   resource :book_comments, only:[:create, :destroy]
   resource :favorites, only: [:create, :destroy]
  end

  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す
  
  get 'searchs/search'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image, destroy: false

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  #　ユーザーを検索
  def User.search(search, user_or_book, how_search)
    if user_or_book == "user"
      if how_search == "match"
        User.where(['name LIKE ?', "#{search}"])
      elsif how_search == "forward"
        User.where(['name LIKE ?', "#{search}%"])
      elsif how_search == "backward"
        User.where(['name LIKE ?', "%#{search}"])
      elsif how_search == "partial"
        User.where(['name LIKE ?', "%#{search}%"])
      else
        User.all
      end
    end
  end

  # 投稿を検索
  def Book.search(search, user_or_book, how_search)
    if user_or_book == "book"
      if how_search == "match"
        Book.where(['title LIKE ?', "#{search}"])
      elsif how_search == "forward"
        Book.where(['title LIKE ?', "#{search}%"])
      elsif how_search == "backward"
        Book.where(['title LIKE ?', "%#{search}"])
      elsif how_search == "partial"
        Book.where(['title LIKE ?', "%#{search}%"])
      else
        Book.all
      end
    end
  end

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :baria_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
    @users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
    @book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "successfully updated user!"
    else
      render "edit"
    end
  end

  def follows
      @user = User.find(params[:id])
      @users = @user.following_user
      render 'follows'
  end

  def followers
      @user = User.find(params[:id])
      @users =@user.follower_user
      render 'followers'
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
    unless params[:id].to_i == current_user.id
      redirect_to user_path(current_user)
    end
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

		<tr>
			<th>follows</th>
			<th><%= link_to "#{user.follower.count}", follows_path(user) %>
			</th>
		</tr>
		<tr>
			<th>followers</th>
			<th><%= link_to "#{user.followed.count}", followers_path(user) %></th>
		</tr>
</table>

<div class="row">
	<% if current_user.id == user.id %>
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	<% end %>

	<%if current_user.id != user.id %>
		<% if current_user.following?(user) %>
			<%= link_to 'フォロー外す', unfollow_path(user.id), class:  "btn btn-primary btn-follow", method: :POST %>
		<% else %>
			<%= link_to 'フォローする', follow_path(user.id), class:  "btn btn-primary btn-follow", method: :POST %>
		<% end %>
	<% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/followers.html.erb
<h1>Follower Users</h1>

<table class="table">
	<thread>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thread>
		<% @user.follower_user.each do |user| %>
			<tr>
				<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				</td>
				<td><%= user.name %></td>
				<td>フォロー数：<%= user.follower.count %></td>
				<td>フォロワー数：<%= user.followed.count %></td>
				<td>
					<%if current_user.id != user.id %>
							<% if current_user.following?(user) %>
								<%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
							<% else %>
								<%= link_to 'フォローする', follow_path(user.id), method: :POST %>
							<% end %>
					<% end %>
				</td>
				<td><%= link_to "Show", user_path(user) %></td>
			</tr>
		<% end %>
</table>

app/views/users/follows.html.erb
<h1>Follow Users</h1>
<table class="table">
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
		<% @user.following_user.each do |user| %>
			<tr>
				<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				</td>
				<td><%= user.name %></td>
				<td>フォロー数：<%= user.follower.count %></td>
				<td>フォロワー数：<%= user.followed.count %></td>
				<td>
					<%if current_user.id != user.id %>
							<% if current_user.following?(user) %>
								<%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
							<% else %>
								<%= link_to 'フォローする', follow_path(user.id), method: :POST %>
							<% end %>
					<% end %>
				</td>
				<td><%= link_to "Show", user_path(user) %></td>
			</tr>
		<% end %>
</table>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

    <div class="col-xs-9">
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
					</td>
					<td><%= user.name%></td>
					<td>フォロー数：<%= user.follower.count %></td>
					<td>フォロワー数：<%= user.followed.count %></td>
					<td>
						<%if current_user.id != user.id %>
							<% if current_user.following?(user) %>
								<%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
							<% else %>
								<%= link_to 'フォローする', follow_path(user.id), method: :POST %>
							<% end %>
						<% end %>
					</td>
					<td><%= link_to "Show", user, class: "user_#{user.id}" %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--users一覧 -->
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
    </div>

    <div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user.id) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>

					<td>
					<p>コメント数 : <%= book.book_comments.count %></p>
				</td>

				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>