config/routes.rb
Rails.application.routes.draw do
  
  root 'home#top'
  get 'home/about'
  devise_for :users
  resources :users
  get 'users/:id/follows'=> 'users#follows', as: 'follows'
  get 'users/:id/followers'=> 'users#followers', as: 'followers'
  
  resources :books do
   resource :book_comments, only:[:create, :destroy]
   resource :favorites, only: [:create, :destroy]
  end

  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す
  
  get 'searchs/search'

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @book_post = Book.find(params[:id])
    @user = @book_post.user
    @book_comment = BookComment.new
    @book = Book.new

  end

  def index
    @books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
    if @book.save #入力されたデータをdbに保存する。
      redirect_to book_path(@book.id), notice: "successfully created book!"#保存された場合の移動先を指定。
    else
      @books = Book.all
      @user = current_user
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
       redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book, notice: "successfully updated book!"
    else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<% if book.errors.any? %>
     <div id="error_explanation">
         <h2><%= book.errors.count %>errors prohibted this book from being saved:</h2>
             <ul>
               <% book.errors.full_messages.each do |message| %>
               <li><%= message %></li>
              <% end %>
              </ul>
     </div>
 <% end %>



<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
 <% if @book.errors.any? %>
     <div id="error_explanation">
         <h2><%= @book.errors.count %>errors prohibted this book from being saved:</h2>
             <ul>
               <% @book.errors.full_messages.each do |message| %>
               <li><%= message %></li>
               <% end %>
              </ul>
     </div>
 <% end %>


<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>

					<td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>

					<td><%= book.body %></td>

					<td><% if book.favorited_by?(current_user) %>
						<%= link_to book_favorites_path(book), method: :delete do %> 
							<i class="glyphicon glyphicon-heart"><%= book.favorites.count%></i>
						<% end %> 
					<% else %><%= link_to book_favorites_path(book), method: :post do %> 
						<i class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></i> 
						<% end %> 
					<% end %>
					</td>

					<td>
						<p>コメント数 : <%= book.book_comments.count %></p>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
			<tr>
				<td>
					<%= link_to user_path(@book_post.user.id) do %>
					<%= attachment_image_tag(@book_post.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
					<%= @book_post.user.name %>
					<% end %>
				</td>
				<td><%= link_to @book_post.title, @book %></td>
				<td><%= @book_post.body %></td>

				<td><% if @book_post.favorited_by?(current_user) %>
						<%= link_to book_favorites_path(@book_post), method: :delete do %> 
							<i class="glyphicon glyphicon-heart"><%= @book_post.favorites.count%></i>
						<% end %> 
					<% else %><%= link_to book_favorites_path(@book_post), method: :post do %> 
						<i class="glyphicon glyphicon-heart-empty"><%= @book_post.favorites.count %></i> 
						<% end %> 
					<% end %>
				</td>

				  
				<td>
					<p>コメント数 : <%= @book_post.book_comments.count %></p>
				</td>

				<% if current_user.id == @book_post.user_id %> 
				<td><%= link_to "Edit",edit_book_path(@book_post), class: "btn-sm btn-success edit_book_#{@book_post.id}" %></td>
				<td><%= link_to "Destroy",@book_post, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book_post.id}" %></td>
				<% end %>
			</tr>
		</table>

		<p><%= @book_post.book_comments.count %>件のコメント</p>
			<table class="table">
				<% @book_post.book_comments.each do |book_comment| %>
				<tr>
					<td width="50">
						<%= attachment_image_tag(book_comment.user, :profile_image, :fill, 40, 40, class: "img-circle pull-left profile-img", fallback: "no-image-mini.jpg") %>
					</td>
					<td width="30">
						<%= book_comment.user.name %>
					</td>
					<td>
						<p><%= book_comment.comment %></p>
					</td>
					<td width="110">
							<%= book_comment.created_at.strftime('%Y/%m/%d') %>
							<% if current_user.id == book_comment.user_id %>
								<%= link_to '', book_book_comments_path(@book_post, book_comment), class: "glyphicon glyphicon-remove", method: :delete %>
							<% end %>
					</td>
				</tr>
				<% end %>
			</table>

		<section>
        <% if @book_comment.errors.any? %>
        <div id="error_explanation">
        	<h2><%= @book_comment.count %>errors prohibted this book from being saved:</h2>
        	<ul>
             	<% @book_comment.full_messages.each do |message| %>
             	<li><%= message %></li>
             	<% end %>
             </ul>
         </div>
         <% end %>

		<%= form_for [@book_post, @book_comment] do |f| %>
            <%= f.text_area :comment, class: "form-control" %>
   				<%= f.submit "送信する", class: "btn btn-primary btn-sm" %>
		<% end %>
		</section>

	</div>
</div>