config/routes.rb
Rails.application.routes.draw do
  
  root 'home#top'
  get 'home/about'
  devise_for :users
  resources :users
  get 'users/:id/follows'=> 'users#follows', as: 'follows'
  get 'users/:id/followers'=> 'users#followers', as: 'followers'
  
  resources :books do
   resource :book_comments, only:[:create, :destroy]
   resource :favorites, only: [:create, :destroy]
  end

  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す
  
  get 'searchs/search'

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
 	def search
 		@user_or_book = params[:option]
 		@how_search = params[:choice]

 		if @user_or_book == "user"
 			@users = User.search(params[:search], @user_or_book, @how_search)
 		else
 			@books = Book.search(params[:search], @user_or_book, @how_search)
 		end
  	end
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searchs/search.html.erb
<% if @user_or_book == "user"%>
    <h1>検索結果</h1>
    <table class="table">
    	<thead>
    		<tr>
                <th>Name</th>
                <th>Introduction</th>
                <th></th>
    		</tr>
    	</thead>
        <% @users.each do |user| %>
        <tdody>
            <tr>
                <td><%= link_to user_path(user.id) do %>
                        <%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
                    <% end %>
                    <br>
                    <%= user.name %>
                </td>
                <td>
                    <%= user.introduction %>
                </td>
                <td><%=link_to "Show", user_path(user.id) %></td>
            </tr>
        </tbody>
        <% end %>
    </table>
 
<% else @user_or_book == "book" %>
    <h1>検索結果</h1>
    <table class="table">
    	<thead>
    		<th>Title</th>
            <th>Opinion</th>
            <th></th>
    	</thead>
    <% @books.each do |book| %>
        <tbody>
            <tr>
                <td><%= book.title %></td>
                <td><%= book.body %></td>
                <td><%= link_to "Show", book_path(book.id) %></td>
            </tr>
        </tbody>
    <% end %>
    </table>
<% end %>